export const ComponentRoutes = {
  LANDING_PAGE:'landing-page',
  NOTFOUND:'not-found',
  DASHBOARD: 'dashboard',
  USERAUTH: 'login',
  LOGIN: '',
  ADMIN_LOGIN: 'admin-login',
  FORGOTPASSWORD: 'forgot-password',
  VERIFYOTP: 'verify-otp',
  VERIFY_AADHAR : 'verify-aadhar',
  NEWPASSWORD: 'new-password',
  HOME: '',
  USER: 'user',
  USERLIST: 'list',
  USERADD: 'add',
  AADHAR_PENDING_USER: 'aadhar-pending-list',
  DELETEUSERLIST: 'delete-user-list',
  CUSTOMER: 'customer',
  CUSTOMERLIST: 'list',
  CUSTOMERADD: 'add',
  VENDOR: 'vendor',
  VENDORLIST: 'list',
  VENDORADD: 'add',
  MANAGEROLE: 'managerole',
  MANAGEROLELIST: 'list',
  MANAGEROLEADD: 'add',
  SERVICECETEGORY: 'serviceCategory',
  SERVICECETEGORYLIST: 'list',
  SERVICECETEGORYADD: 'add',
  BOOKING: 'booking',
  BOOKINGLIST: 'list',
  BOOKINGADD: 'add',
  PROFILE: 'profile',
};
